dataset_path: pkulium/I-ScienceQA
dataset_name: insert_hint
task: "I-ScienceQA_insert_hint_few_shot"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.sqa_doc_to_visual
doc_to_text: !function utils.sqa_doc_to_text
doc_to_target: !function utils.sqa_doc_to_target
generation_kwargs:
  max_new_tokens: 128
  temperature: 0
  do_sample: False
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils.sqa_process_results_few_shot
metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    format: default
    pre_prompt: ""
    post_prompt: "\nProvide the answer by selecting the option's letter from the given choices first, then give a brief reasoning for your selection."
    shot_number: 0
  qwen_vl:
    format: qwen_vl
  idefics2:
    format: default
    pre_prompt: ""
    post_prompt: "\nAnswer:"
model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original
  
