name: minigptv
channels:
  - conda-forge
  - rapidsai
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.2=h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.3.3
      - aiohttp==3.10.0
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - av==13.0.0
      - bitsandbytes==0.37.0
      - black==24.1.0
      - braceexpand==0.1.7
      - brotli==1.1.0
      - certifi==2024.7.4
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cma==3.4.0
      - cmake==3.30.1
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==2.16.1
      - decorator==5.1.1
      - decord==0.6.0
      - dill==0.3.7
      - distlib==0.3.8
      - distro==1.9.0
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - email-validator==2.2.0
      - et-xmlfile==1.1.0
      - evaluate==0.4.2
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastapi==0.111.1
      - fastapi-cli==0.0.4
      - ffmpy==0.4.0
      - filelock==3.15.4
      - flash-attn==2.6.3
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fschat==0.2.36
      - fsspec==2023.10.0
      - ftfy==6.2.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.16.0
      - gradio-client==0.8.1
      - h11==0.14.0
      - hf-transfer==0.1.8
      - httpcore==0.16.3
      - httptools==0.6.1
      - httpx==0.24.0
      - huggingface-hub==0.24.0
      - identify==2.6.0
      - idna==3.7
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipython==8.18.1
      - isort==5.13.2
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - latex2mathml==3.77.0
      - lazy-loader==0.4
      - lit==18.1.8
      - llava==1.2.2.post1
      - lmms-eval==0.2.3.post1
      - loguru==0.7.2
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markdown2==2.5.0
      - markupsafe==2.1.5
      - matplotlib==3.7.0
      - matplotlib-inline==0.1.7
      - mbstrdecoder==1.1.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.15
      - mutagen==1.47.0
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nh3==0.2.18
      - nltk==3.8.1
      - nodeenv==1.9.1
      - numexpr==2.10.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.44.0
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - orjson==3.10.6
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pathspec==0.12.1
      - pathvalidate==3.2.1
      - peft==0.2.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - portalocker==2.10.1
      - pre-commit==3.8.0
      - progressbar2==4.4.2
      - prompt-toolkit==3.0.47
      - protobuf==3.20.0
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pybind11==2.13.5
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycryptodomex==3.20.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pytablewriter==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - python-utils==3.8.2
      - pytz==2024.1
      - pyyaml==6.0
      - referencing==0.35.1
      - regex==2022.10.31
      - requests==2.32.3
      - rfc3986==1.5.0
      - rich==13.7.1
      - rpds-py==0.19.1
      - ruff==0.6.4
      - sacrebleu==2.4.3
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scikit-learn==1.2.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - stack-data==0.6.3
      - starlette==0.37.2
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - tenacity==8.3.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - tiktoken==0.7.0
      - timm==1.0.9
      - tokenizers==0.15.1
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.1.2
      - torchaudio==2.0.1
      - torchvision==0.16.2
      - tqdm==4.64.1
      - tqdm-multiprocess==0.0.11
      - traitlets==5.14.3
      - transformers==4.37.2
      - transformers-stream-generator==0.0.5
      - triton==2.1.0
      - typepy==1.3.2
      - typer==0.12.3
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - uvicorn==0.30.3
      - uvloop==0.19.0
      - virtualenv==20.26.3
      - visual-genome==1.1.1
      - wandb==0.17.5
      - watchfiles==0.22.0
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webdataset==0.2.48
      - websockets==11.0.3
      - xxhash==3.5.0
      - yarl==1.9.4
      - yt-dlp==2024.8.6
      - zipp==3.19.2
      - zss==1.2.0
      - zstandard==0.23.0
prefix: /work/LAS/wzhang-lab/mingl/.conda/envs/minigptv
